### ISSUE TITLE
Clipboard is not a constructor

### ISSUE THREAD

**Issue by dfa1234** [sachinchoolur/ngclipboard#18]
It seems that is n't working

angular.js:13424 TypeError: Clipboard is not a constructor
    at link (http://localhost/~dfa/admindk/bower_components/ngclipboard/dist/ngclipboard.js:27:33)
    at http://localhost/~dfa/admindk/bower_components/angular/angular.min.js:79:486
    at ja (http://localhost/~dfa/admindk/bower_components/angular/angular.min.js:80:35)
    at n (http://localhost/~dfa/admindk/bower_components/angular/angular.min.js:65:220)
    at g (http://localhost/~dfa/admindk/bower_components/angular/angular.min.js:58:140)
    at n (http://localhost/~dfa/admindk/bower_components/angular/angular.min.js:65:165)
    at g (http://localhost/~dfa/admindk/bower_components/angular/angular.min.js:58:140)
    at n (http://localhost/~dfa/admindk/bower_components/angular/angular.min.js:65:165)
    at g (http://localhost/~dfa/admindk/bower_components/angular/angular.min.js:58:140)
    at n (http://localhost/~dfa/admindk/bower_components/angular/angular.min.js:65:165) <button class="md-raised md-primary ports md-button ng-isolate-scope" ng-transclude="" style="margin-left:10px" ngclipboard="" data-clipboard-target="#bar" data-clipboard-action="cut">

**Comment by sachinchoolur** [comment]
Please provide a jsfiddle demo for your setup..

**Comment by leogout** [comment]
Remember to include the Clipboard.js file first.

**Comment by stacieweff** [comment]
I am getting this same error as well. Has there been a fix or a find for the issue?

**Comment by leogout** [comment]
Let me guess : you did not included the clipboard.js file as I mentioned right above.

``` javascript
<script src="dist/clipboard.min.js"></script>
<script src="dist/ngclipboard.min.js"></script>
```

**Comment by stacieweff** [comment]
thanks. sorry, I am super new to angular.

**Comment by afialho** [comment]
I am getting this same error as well. Has there been a fix or a find for the issue?:) 
I'm including "clipboard.js" before "ngclipboard" with requirejs, but have error "Clipboard is not a constructor". I user "clipboard.js v1.5.10" and "ngclipboard - v1.1.1".

**Comment by salmanasiddiqui** [comment]
Having same error.

I dont want to load clipboard via script tag as mentioned on the README, I am using requireJS to load ngclipboard and clipboard. I have also defined clipboard as dependency of ngclipboard so that requireJS will load clipboard before loading ngclipboard.

But it just doesnt work, Same error stack as above.

in ngclipboard.js, it loads sets the angular from window.angular.. but window.Clipboard is always undefined.

**Comment by guicoma** [comment]
+1.
I guess I'm hopping on the requireJS-problem wagon.

**Comment by che85** [comment]
I am having the same issue when loading via requirejs

**Comment by che85** [comment]
As a workaround I did the following in my main.js

```
require.config({
  paths: {
    "angular": "../bower_components/angular/angular",
    "jquery": "../bower_components/jquery/dist/jquery.min",
    "clipboard": "../bower_components/clipboard/dist/clipboard.min",
    "ngclipboard": "../bower_components/ngclipboard/dist/ngclipboard.min",
    "app": "app"
  },
  shim: {
    "angular": {
      deps: ["jquery"]
    },
    "app": {
      deps: ["angular", "ngclipboard"]
    },
    "ngclipboard": {
      deps: ["angular", "clipboard"]
    }
  }
});

require(['clipboard'], function(clipboard) {
  window.Clipboard = clipboard;
});

require(["app"],
  function () {
    angular.bootstrap(document, ["app"]);
  }
);
```

The most important part obviously is:

```
require(['clipboard'], function(clipboard) {
  window.Clipboard = clipboard;
});
```

This works fine for me.

**Comment by antonkronaj** [comment]
To add to @che85 answer. 
I had to assign `Window.ClipboardJS = clipboard;`. Also, it **was** important to do 
```
require(['clipboard'], function(clipboard) {
	window.ClipboardJS = clipboard;
});
```
before, and separately from, bootstrapping the app.

**Comment by Samee1905** [comment]
angular.js:14199 TypeError: ClipboardJS is not a constructor
    at Object.link (<anonymous>:28:33)
    at http://scdevapp13.corp.amdocs.com:8000/widget/app/*****/components/uniprovision/template/bower_components/angular/angular.min.js?ossVersion=202002111807:16:71
    at http://scdevapp13.corp.amdocs.com:8000/widget/app/*****/components/uniprovision/template/bower_components/angular/angular.min.js?ossVersion=202002111807:82:187
    at sa (http://scdevapp13.corp.amdocs.com:8000/widget/app/*****/components/uniprovision/template/bower_components/angular/angular.min.js?ossVersion=202002111807:82:244)
    at n (http://scdevapp13.corp.amdocs.com:8000/widget/app/*****/components/uniprovision/template/bower_components/angular/angular.min.js?ossVersion=202002111807:68:6)
    at g (http://scdevapp13.corp.amdocs.com:8000/widget/app/*****/components/uniprovision/template/bower_components/angular/angular.min.js?ossVersion=202002111807:59:428)
    at g (http://scdevapp13.corp.amdocs.com:8000/widget/app/*****/components/uniprovision/template/bower_components/angular/angular.min.js?ossVersion=202002111807:59:445)
    at g (http://scdevapp13.corp.amdocs.com:8000/widget/app/******/components/uniprovision/template/bower_components/angular/angular.min.js?ossVersion=202002111807:59:445)
    at n (http://scdevapp13.corp.amdocs.com:8000/widget/app/*****/components/uniprovision/template/bower_components/angular/angular.min.js?ossVersion=202002111807:67:452)
    at g (http://scdevapp13.corp.amdocs.com:8000/widget/app/*****/components/uniprovision/template/bower_components/angular/angular.min.js?ossVersion=202002111807:59:428) <a ngclipboard="" data-clipboard-action="copy" data-clipboard-text="Just" class="ng-isolate-scope">

**Comment by Samee1905** [comment]
I am using angular v1.5.11, does it matter?
